<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cities')->insert([
            ['name' => 'Akmenė'],
            ['name' => 'Alytus'],
            ['name' => 'Anykščiai'],
            ['name' => 'Ariogala'],
            ['name' => 'Baltoji Vokė'],
            ['name' => 'Birštonas'],
            ['name' => 'Biržai'],
            ['name' => 'Daugai'],
            ['name' => 'Druskininkai'],
            ['name' => 'Dūkštas'],
            ['name' => 'Dusetos'],
            ['name' => 'Eišiškės'],
            ['name' => 'Elektrėnai'],
            ['name' => 'Ežerėlis'],
            ['name' => 'Garliava'],
            ['name' => 'Gargždai'],
            ['name' => 'Gelgaudiškis'],
            ['name' => 'Grigiškės'],
            ['name' => 'Ignalina'],
            ['name' => 'Jieznas'],
            ['name' => 'Jonava'],
            ['name' => 'Joniškėlis'],
            ['name' => 'Joniškis'],
            ['name' => 'Jurbarkas'],
            ['name' => 'Kaišiadorys'],
            ['name' => 'Kalvarija'],
            ['name' => 'Kaunas'],
            ['name' => 'Kazlų Rūda'],
            ['name' => 'Kėdainiai'],
            ['name' => 'Kelmė'],
            ['name' => 'Klaipėda'],
            ['name' => 'Kretinga'],
            ['name' => 'Kudirkos Naumiestis'],
            ['name' => 'Kupiškis'],
            ['name' => 'Kuršėnai'],
            ['name' => 'Kybartai'],
            ['name' => 'Lazdijai'],
            ['name' => 'Lentvaris'],
            ['name' => 'Linkuva'],
            ['name' => 'Mažeikiai'],
            ['name' => 'Marijampolė'],
            ['name' => 'Molėtai'],
            ['name' => 'Naujoji Akmenė'],
            ['name' => 'Nemenčinė'],
            ['name' => 'Neringa'],
            ['name' => 'Obeliai'],
            ['name' => 'Pagėgiai'],
            ['name' => 'Pakruojis'],
            ['name' => 'Palanga'],
            ['name' => 'Panevėžys'],
            ['name' => 'Panemunė'],
            ['name' => 'Pasvalys'],
            ['name' => 'Pabradė'],
            ['name' => 'Plungė'],
            ['name' => 'Prienai'],
            ['name' => 'Priekulė'],
            ['name' => 'Radviliškis'],
            ['name' => 'Ramygala'],
            ['name' => 'Raseiniai'],
            ['name' => 'Rietavas'],
            ['name' => 'Rokiškis'],
            ['name' => 'Rūdiškės'],
            ['name' => 'Salantai'],
            ['name' => 'Seda'],
            ['name' => 'Simnas'],
            ['name' => 'Skuodas'],
            ['name' => 'Smalininkai'],
            ['name' => 'Subačius'],
            ['name' => 'Šakiai'],
            ['name' => 'Šalčininkai'],
            ['name' => 'Šeduva'],
            ['name' => 'Šiauliai'],
            ['name' => 'Šilalė'],
            ['name' => 'Šilutė'],
            ['name' => 'Širvintos'],
            ['name' => 'Švenčionėliai'],
            ['name' => 'Švenčionys'],
            ['name' => 'Tauragė'],
            ['name' => 'Telšiai'],
            ['name' => 'Tytuvėnai'],
            ['name' => 'Trakai'],
            ['name' => 'Troškūnai'],
            ['name' => 'Ukmergė'],
            ['name' => 'Utena'],
            ['name' => 'Užventis'],
            ['name' => 'Vabalninkas'],
            ['name' => 'Varėna'],
            ['name' => 'Varniai'],
            ['name' => 'Venta'],
            ['name' => 'Veisiejai'],
            ['name' => 'Viekšniai'],
            ['name' => 'Vilkaviškis'],
            ['name' => 'Vilkija'],
            ['name' => 'Vilnius'],
            ['name' => 'Virbalis'],
            ['name' => 'Visaginas'],
            ['name' => 'Zarasai'],
            ['name' => 'Žagarė'],
            ['name' => 'Žiežmariai']
        ]);
    }
}
