version: '3.8'

services:
  php:
    image: php:fpm
    container_name: php-container
    volumes:
      - /home/evdm0167/website/public:/home/evdm0167/website/public  # Make sure to map the whole website directory
    networks:
      - my_network
    ports:
      - "9000:9000"  # Explicitly bind port 9000 to the host machine

  nginx:
    image: nginx:latest
    container_name: nginx-container
    depends_on:
      - php
    volumes:
      - /home/evdm0167/website:/home/evdm0167/website  # Map the website directory
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   # Map nginx.conf to container
    ports:
      - "80:80"
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

networks:
  my_network:

volumes:
  pgdata:
