version: '3.8'

services:
  php:
    image: php:fpm
    container_name: php-container
    volumes:
      - ./webserver:/var/www/html
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    depends_on:
      - php
    volumes:
      - ./webserver:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

networks:
  my_network:

volumes:
  pgdata:
